# Exercise 13: Predictions with more data

## Beginner

Here's a simple widget that you can use to add more data and fit the linear regression model automatically.

Use the widget to add the details of a sixth cabin so that the data is as follows. Observe how the regression model adapts to your newly inputted data and changes the cabins' predicted prices.

Train the model

Estimated Coefficients

What happens to the predictions of the prices of the first five cabins?

they become less accurate

## Intermediate

Try modifying the code below by adding the numbers for a sixth cabin into the data so that you have the following data set. Do not change the print statements.

cabin 1	25	2	50	1	500	    127,900
cabin 2	39	3	10	1	1000	222,100
cabin 3	13	2	13	1	1000	143,750
cabin 4	82	5	20	2	120	    268,000
cabin 5	130	6	10	2	600	    460,700
cabin 6	115	6	10	1	550	    407,000

In [1]:
import numpy as np

def main():
    np.set_printoptions(precision=1)

    x = np.array(
        [
            [25, 2, 50, 1, 500],
            [39, 3, 10, 1, 1000],
            [13, 2, 13, 1, 1000],
            [82, 5, 20, 2, 120],
            [130, 6, 10, 2, 600],
            [115, 6, 10, 1, 550]
        ]
    )

    y = np.array([127900, 222100, 143750, 268000, 460700, 407000])

    c = np.linalg.lstsq(x, y)[0]
    print(c)

    print(x @ c)

main()


[2989.6  800.6  -44.8 3890.8   99.8]
[127907.6 222269.8 143604.5 268017.6 460686.6 406959.9]


C:\Users\Tal I\AppData\Local\Temp\ipykernel_3884\1635212252.py:19: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  c = np.linalg.lstsq(x, y)[0]


## Advanced

Write a program that reads cabin details and prices from a CSV file (a standard format for tabular data) and fits a linear regression model to it. The program should be able to handle any number of data points (cabins) described by any number of features (like size, size of sauna, number of bathrooms, ...).

You can read a CSV file with the function np.genfromtxt(datafile, skip_header=1). This will return a numpy array that contains the feature data in the columns preceding the last one, and the price data in the last column. The option skip_header=1 just means that the first line in the file is supposed to contain just the column names and shouldn't be included in the actual data.

The output of the program should be the estimated coefficients and the predicted or "fitted" prices for the same set of cabins used to estimate the parameters. So if you fit the model using data for six cabins with known prices, the program will print out the prices that the model predicts for those six cabins (even if the actual prices are already given in the data).

Note that here we will actually only simulate the file input using Python's io.StringIO function that takes an input string and pretends that the contents is coming from a file. In practice, you would just name the input file that contains the data in the same format as the string input below.

Hint:

You can read the contents of the "file" (or in this case, the input string) using the np.genfromtxt function (check out [this](https://stackoverflow.com/q/24027040) stackoverflow answer for help with the dimensionality), and fit the data using np.linalg.lstsq.

In [35]:
import numpy as np
from io import StringIO

input_string = '''
25 2 50 1 500 127900
39 3 10 1 1000 222100
13 2 13 1 1000 143750
82 5 20 2 120 268000
130 6 10 2 600 460700
115 6 10 1 550 407000
'''

np.set_printoptions(precision=1)    # this just changes the output settings for easier reading

def fit_model(input_file):
    # Please write your code inside this function
    input_array = np.genfromtxt(input_file, skip_header=1)
    # read the data in and fit it. the values below are placeholder values
    x = input_array[:,:-1]  # all except last column
    # y = input_array[:,5:]  # last column, but we need data of y in row

    y = []
    for i in range(len((input_array))):
        y.append(input_array[i][-1])
    # print(x)
    # print(y)
    y = np.asarray(y)

    c = np.linalg.lstsq(x, y)[0]

    print(c)
    print(x @ c)

# simulate reading a file

input_file = StringIO(input_string)
fit_model(input_file)


[2989.6  800.6  -44.8 3890.8   99.8]
[127907.6 222269.8 143604.5 268017.6 460686.6 406959.9]


C:\Users\Tal I\AppData\Local\Temp\ipykernel_3884\3566719638.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  c = np.linalg.lstsq(x, y)[0]
